// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRp-fchm975O2evcIcSORB2j5RI0jk1bo',
    appId: '1:254197365724:web:c616a7393ab2494f476d19',
    messagingSenderId: '254197365724',
    projectId: 'test-app-394cc',
    authDomain: 'test-app-394cc.firebaseapp.com',
    storageBucket: 'test-app-394cc.appspot.com',
    measurementId: 'G-9EMVNZ5D7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wK_2CxZtbzZ4sYLz5WQ6ua5AbU2Ixzw',
    appId: '1:254197365724:android:ff47026bc1e6b994476d19',
    messagingSenderId: '254197365724',
    projectId: 'test-app-394cc',
    storageBucket: 'test-app-394cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAedOLwPS8q7WY1DWNZeM52wlXK2ZFU6A',
    appId: '1:254197365724:ios:65965aed48e9b227476d19',
    messagingSenderId: '254197365724',
    projectId: 'test-app-394cc',
    storageBucket: 'test-app-394cc.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAedOLwPS8q7WY1DWNZeM52wlXK2ZFU6A',
    appId: '1:254197365724:ios:65965aed48e9b227476d19',
    messagingSenderId: '254197365724',
    projectId: 'test-app-394cc',
    storageBucket: 'test-app-394cc.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRp-fchm975O2evcIcSORB2j5RI0jk1bo',
    appId: '1:254197365724:web:777ae293060de862476d19',
    messagingSenderId: '254197365724',
    projectId: 'test-app-394cc',
    authDomain: 'test-app-394cc.firebaseapp.com',
    storageBucket: 'test-app-394cc.appspot.com',
    measurementId: 'G-EJZXQ7ETJ1',
  );
}
